# Generated by Django 5.2.7 on 2025-10-30 23:41

import apps.archive.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, unique=True, verbose_name='NIP')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('position', models.CharField(max_length=100, verbose_name='Jabatan')),
                ('department', models.CharField(max_length=100, verbose_name='Unit Kerja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
                'db_table': 'employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-folder', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archive.documentcategory')),
            ],
            options={
                'verbose_name': 'Kategori Dokumen',
                'verbose_name_plural': 'Kategori Dokumen',
                'db_table': 'document_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.archive.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='File PDF')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Ukuran File (bytes)')),
                ('document_date', models.DateField(verbose_name='Tanggal Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='archive.documentcategory')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'db_table': 'documents',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan Sistem',
                'verbose_name_plural': 'Pengaturan Sistem',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='SPDDocument',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spd_info', serialize=False, to='archive.document')),
                ('destination', models.CharField(choices=[('balikpapan', 'Balikpapan'), ('samarinda', 'Samarinda'), ('bontang', 'Bontang'), ('kutai_kartanegara', 'Kutai Kartanegara'), ('paser', 'Paser'), ('berau', 'Berau'), ('kutai_barat', 'Kutai Barat'), ('kutai_timur', 'Kutai Timur'), ('penajam_paser_utara', 'Penajam Paser Utara'), ('mahakam_ulu', 'Mahakam Ulu'), ('jakarta', 'Jakarta'), ('surabaya', 'Surabaya'), ('makassar', 'Makassar'), ('banjarmasin', 'Banjarmasin'), ('yogyakarta', 'Yogyakarta'), ('bandung', 'Bandung'), ('semarang', 'Semarang'), ('denpasar', 'Denpasar'), ('other', 'Lainnya')], max_length=100, verbose_name='Tujuan')),
                ('destination_other', models.CharField(blank=True, help_text="Isi jika memilih 'Lainnya'", max_length=255, null=True, verbose_name='Tujuan Lainnya')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spd_documents', to='archive.employee', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Dokumen SPD',
                'verbose_name_plural': 'Dokumen SPD',
                'db_table': 'spd_documents',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Dibuat'), ('view', 'Dilihat'), ('download', 'Diunduh'), ('update', 'Diperbarui'), ('delete', 'Dihapus')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='archive.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktivitas Dokumen',
                'verbose_name_plural': 'Aktivitas Dokumen',
                'db_table': 'document_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='document_ac_documen_b2bd1a_idx'), models.Index(fields=['user', '-created_at'], name='document_ac_user_id_0f3d60_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_date'], name='documents_documen_718437_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'document_date'], name='documents_categor_0a699b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='documents_created_32bb74_idx'),
        ),
    ]
