# Generated by Django 5.2.7 on 2025-10-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_remove_document_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
